#!/bin/sh

# first build the image after cloning this repository
# docker build -t apidoc/apidoc ./.docker/apidoc

# run apidoc
mkdir -p ./src/web/apidocs/
chmod -R 777 ./src/web/apidocs/

docker run --rm \
  -v $(pwd):/home/node/apidoc \
  yao3060/apidoc -i src/controllers/ -o ./src/web/apidocs/

echo "Apidoc generated"
